// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackOffice_WebAPI
{
    public partial class Article
    {
        public string CodeArt { get; set; }
        public string TypeCategorie { get; set; }
        public short? NumCategorie { get; set; }
        public string Conditionnement { get; set; }
        public decimal? Quantite { get; set; }
        public decimal? PrixVente { get; set; }
        public string Designation { get; set; }
        public string N1 { get; set; }
        public string N2 { get; set; }
        public string N3 { get; set; }
        public string N4 { get; set; }
        public int? iN1 { get; set; }
        public int? iN2 { get; set; }
        public int? iN3 { get; set; }
        public int? iN4 { get; set; }
    }
}