// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackOffice_WebAPI
{
    public partial class F_ARTICLE
    {
        public F_ARTICLE()
        {
            F_DOCLIGNEs = new HashSet<F_DOCLIGNE>();
            InverseAR_SubstitutNavigation = new HashSet<F_ARTICLE>();
        }

        public string AR_Ref { get; set; }
        public byte[] cbAR_Ref { get; set; }
        public string AR_Design { get; set; }
        public byte[] cbAR_Design { get; set; }
        public string FA_CodeFamille { get; set; }
        public byte[] cbFA_CodeFamille { get; set; }
        public string AR_Substitut { get; set; }
        public byte[] cbAR_Substitut { get; set; }
        public string AR_Raccourci { get; set; }
        public byte[] cbAR_Raccourci { get; set; }
        public short? AR_Garantie { get; set; }
        public short? AR_UnitePoids { get; set; }
        public decimal? AR_PoidsNet { get; set; }
        public decimal? AR_PoidsBrut { get; set; }
        public short? AR_UniteVen { get; set; }
        public decimal? AR_PrixAch { get; set; }
        public decimal? AR_Coef { get; set; }
        public decimal? AR_PrixVen { get; set; }
        public short? AR_PrixTTC { get; set; }
        public short? AR_Gamme1 { get; set; }
        public short? AR_Gamme2 { get; set; }
        public short? AR_SuiviStock { get; set; }
        public short? AR_Nomencl { get; set; }
        public string AR_Stat01 { get; set; }
        public string AR_Stat02 { get; set; }
        public string AR_Stat03 { get; set; }
        public string AR_Stat04 { get; set; }
        public string AR_Stat05 { get; set; }
        public short? AR_Escompte { get; set; }
        public short? AR_Delai { get; set; }
        public short? AR_HorsStat { get; set; }
        public short? AR_VteDebit { get; set; }
        public short? AR_NotImp { get; set; }
        public short? AR_Sommeil { get; set; }
        public string AR_Langue1 { get; set; }
        public string AR_Langue2 { get; set; }
        public string AR_EdiCode { get; set; }
        public string AR_CodeBarre { get; set; }
        public byte[] cbAR_CodeBarre { get; set; }
        public string AR_CodeFiscal { get; set; }
        public string AR_Pays { get; set; }
        public string AR_Frais01FR_Denomination { get; set; }
        public decimal? AR_Frais01FR_Rem01REM_Valeur { get; set; }
        public short? AR_Frais01FR_Rem01REM_Type { get; set; }
        public decimal? AR_Frais01FR_Rem02REM_Valeur { get; set; }
        public short? AR_Frais01FR_Rem02REM_Type { get; set; }
        public decimal? AR_Frais01FR_Rem03REM_Valeur { get; set; }
        public short? AR_Frais01FR_Rem03REM_Type { get; set; }
        public string AR_Frais02FR_Denomination { get; set; }
        public decimal? AR_Frais02FR_Rem01REM_Valeur { get; set; }
        public short? AR_Frais02FR_Rem01REM_Type { get; set; }
        public decimal? AR_Frais02FR_Rem02REM_Valeur { get; set; }
        public short? AR_Frais02FR_Rem02REM_Type { get; set; }
        public decimal? AR_Frais02FR_Rem03REM_Valeur { get; set; }
        public short? AR_Frais02FR_Rem03REM_Type { get; set; }
        public string AR_Frais03FR_Denomination { get; set; }
        public decimal? AR_Frais03FR_Rem01REM_Valeur { get; set; }
        public short? AR_Frais03FR_Rem01REM_Type { get; set; }
        public decimal? AR_Frais03FR_Rem02REM_Valeur { get; set; }
        public short? AR_Frais03FR_Rem02REM_Type { get; set; }
        public decimal? AR_Frais03FR_Rem03REM_Valeur { get; set; }
        public short? AR_Frais03FR_Rem03REM_Type { get; set; }
        public short? AR_Condition { get; set; }
        public decimal? AR_PUNet { get; set; }
        public short? AR_Contremarque { get; set; }
        public short? AR_FactPoids { get; set; }
        public short? AR_FactForfait { get; set; }
        public short? AR_SaisieVar { get; set; }
        public short? AR_Transfere { get; set; }
        public short? AR_Publie { get; set; }
        public DateTime? AR_DateModif { get; set; }
        public string AR_Photo { get; set; }
        public decimal? AR_PrixAchNouv { get; set; }
        public decimal? AR_CoefNouv { get; set; }
        public decimal? AR_PrixVenNouv { get; set; }
        public DateTime? AR_DateApplication { get; set; }
        public decimal? AR_CoutStd { get; set; }
        public decimal? AR_QteComp { get; set; }
        public decimal? AR_QteOperatoire { get; set; }
        public int? CO_No { get; set; }
        public int? cbCO_No { get; set; }
        public short? AR_Prevision { get; set; }
        public int? CL_No1 { get; set; }
        public int? cbCL_No1 { get; set; }
        public int? CL_No2 { get; set; }
        public int? cbCL_No2 { get; set; }
        public int? CL_No3 { get; set; }
        public int? cbCL_No3 { get; set; }
        public int? CL_No4 { get; set; }
        public int? cbCL_No4 { get; set; }
        public short? AR_Type { get; set; }
        public string RP_CodeDefaut { get; set; }
        public short? AR_Nature { get; set; }
        public short? AR_DelaiFabrication { get; set; }
        public short? AR_NbColis { get; set; }
        public short? AR_DelaiPeremption { get; set; }
        public short? AR_DelaiSecurite { get; set; }
        public short? AR_Fictif { get; set; }
        public short? AR_SousTraitance { get; set; }
        public short? AR_TypeLancement { get; set; }
        public short? cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public short? cbFlag { get; set; }
        public string Promo { get; set; }
        public string Marque { get; set; }
        public string Fournisseur { get; set; }
        public decimal? Stock_OL { get; set; }
        public decimal? PVU { get; set; }
        public decimal? Colisage { get; set; }
        public string ACODE { get; set; }
        public string STATUT { get; set; }
        public decimal? PrixPu { get; set; }
        public string PROMOTION { get; set; }
        public string COULEUR { get; set; }
        public DateTime? cbCreation { get; set; }
        public Guid? cbCreationUser { get; set; }
        public byte[] cbAR_EdiCode { get; set; }
        public short? AR_Cycle { get; set; }
        public short? AR_Criticite { get; set; }

        public virtual F_ARTICLE AR_SubstitutNavigation { get; set; }
        public virtual ICollection<F_DOCLIGNE> F_DOCLIGNEs { get; set; }
        public virtual ICollection<F_ARTICLE> InverseAR_SubstitutNavigation { get; set; }
    }
}