// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackOffice_WebAPI
{
    public partial class F_CATALOGUEV
    {
        public int? Id { get; set; }
        public string name { get; set; }
        public int? parentId { get; set; }
    }
}