// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackOffice_WebAPI
{
    public partial class N1Clt
    {
        public string Id_Client { get; set; }
        public string Nom_Client { get; set; }
        public string Pays { get; set; }
        public string Ville { get; set; }
        public string Region { get; set; }
        public string Adresse { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Categorie_Tarifaire { get; set; }
        public int? Id_Commercial { get; set; }
        public string Code_Commercial { get; set; }
        public string Nom_Commercial { get; set; }
    }
}