// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BackOffice_WebAPI
{
    public partial class VM_Collaborateur
    {
        public int id { get; set; }
        public string Login { get; set; }
        public string Psw { get; set; }
        public int? CO_NO { get; set; }
        public int? PROFIL { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string CT_Num { get; set; }
        public string RegistrationID { get; set; }
        public int? N_cattarif { get; set; }
    }
}